In [4]:
# Part 1 - attempt 1 (out of memory)
# creating 1:1 map (out of data)

file_data = open('input.txt','r')
lines = file_data.readlines()

test_data = open('test.txt','r')
test = test_data.readlines()

use_data = lines

maps = []

for i in range(0,7) :
    maps.append(list(range(0,9999999999)))

print(maps)

map_counter = -2

# update maps

nums = []

for line in use_data :
    skip = False
    if len(line) == 1:
        skip = True
    elif not line[0].isnumeric():
        skip = True
        map_counter += 1
    
    if not skip :
        #update maps
        nums = line.split()

        dest_start = int(nums[0])
        index_start = int(nums[1])
        range_length = int(nums[2])

        for i in range(range_length) :
            maps[map_counter][index_start + i] = dest_start + i
        
# put seed through maps

seeds = use_data[0][7:].split()
minimum = -1

for seed in seeds :
    seed = int(seed)

    for map in maps :
        seed = map[seed]

    if minimum == -1 :
        minimum = seed
    else :
        minimum = min(minimum,seed)

print(minimum)
        

MemoryError: 

In [28]:
# Part 1 attempt 2 - map class


class RangeMap():
    def __init__(self):
        self.mapping_rules = []
    
    def add_mapping_rule(self, start, end, increment):
        rule = {'start': start, 'end': end, 'increment': increment}
        self.mapping_rules.append(rule)
    
    def map_value(self, x):
        for rule in self.mapping_rules:
            if rule['start'] <= x <= rule['end']:
                return x + rule['increment']
        # If no rule matches, return the original value
        return x
    

file_data = open('input.txt','r')
lines = file_data.readlines()

test_data = open('test.txt','r')
test = test_data.readlines()

use_data = test

maps = []

for i in range(0,7) :
    new_map = RangeMap()
    maps.append(new_map) 

map_counter = -2

# update maps

nums = []

for line in use_data :
    skip = False
    if len(line) == 1:
        skip = True
    elif not line[0].isnumeric():
        skip = True
        map_counter += 1
    
    if not skip :
        #update maps
        nums = line.split()

        dest_start = int(nums[0])
        index_start = int(nums[1])
        range_length = int(nums[2])

        maps[map_counter].add_mapping_rule(index_start,index_start+range_length,dest_start - index_start)

        
        
# put seed through maps
# initialise seeds
seeds = use_data[0][7:].split()
minimum = -1
print(seeds)

for seed in seeds :
    seed = int(seed)

    for map in maps :
        seed = map.map_value(seed)

    print(minimum)

    if minimum == -1 :
        minimum = seed
    else :
        minimum = min(minimum,seed)

print(minimum)


['79', '14', '55', '13']
-1
82
43
43
35


In [29]:
# Part 2
# Initialise seeds

use_data = test

seed_data = use_data[0][7:].split()
seeds = []

minimum = -1

for i in range(int(len(seed_data)/2)) :
    
    seeds = seeds + list(range(int(seed_data[2*i]) , int(seed_data[2*i]) + int(seed_data[2*i + 1])))

print(seeds)

for seed in seeds :
    
    for map in maps :
        seed = map.map_value(seed)

    print(seed)
    
    if minimum == -1 :
        minimum = seed
    else :
        minimum = min(minimum,seed)


print(minimum)


[79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]
82
83
84
46
47
48
49
50
51
52
53
54
55
60
86
87
88
89
90
95
96
97
57
58
59
60
98
46


In [30]:
import numpy as np


class RangeMap():
    def __init__(self):
        self.mapping_rules = []
    
    def add_mapping_rule(self, start, end, increment):
        rule = {'start': start, 'end': end, 'increment': increment}
        self.mapping_rules.append(rule)
    
    def map_values(self, values):
        result = np.array(values, dtype=float)
        mapped_result = np.array(values, dtype=float)   

        sorted_rules = sorted(self.mapping_rules, key=lambda x: x['start'])

        print(sorted_rules)

        for rule in sorted_rules:
            if rule['start'] <= current_end:
                current_end = max(current_end, rule['end'])
                current_increment += rule['increment']
            else:
                mask = np.logical_and(result >= current_start, result < current_end)
                mapped_result[mask] += current_increment
                
                current_start = rule['start']
                current_end = rule['end']
                current_increment = rule['increment']
            
            #print(result)
            #print(rule)
            mask = np.logical_and(result >= current_start, result < current_end)
            mapped_result[mask] += current_increment
            #print(mask)
            #print(mapped_result)
            #print()

        return mapped_result
    

file_data = open('input.txt','r')
lines = file_data.readlines()

test_data = open('test.txt','r')
test = test_data.readlines()

use_data = test

maps = []

for i in range(0,7) :
    new_map = RangeMap()
    maps.append(new_map) 

map_counter = -2

# update maps

nums = []

for line in use_data :
    skip = False
    if len(line) == 1:
        skip = True
    elif not line[0].isnumeric():
        skip = True
        map_counter += 1
    
    if not skip :
        #update maps
        nums = line.split()

        dest_start = int(nums[0])
        index_start = int(nums[1])
        range_length = int(nums[2])

        maps[map_counter].add_mapping_rule(index_start,index_start+range_length,dest_start - index_start)


seed_data = use_data[0][7:].split()
seed_data_array = np.array(seed_data,dtype='int64')

minimum_number = -1

values = np.concatenate([np.arange(start, start + end) for start, end in zip(seed_data_array[::2], seed_data_array[1::2])])

print(len(values))

for map in maps :
    values = map.map_values(values)

min_value = np.min(values)

if minimum_number == -1 :
    minimum_number = min_value
else :
    minimum_number = np.min([minimum_number,min_value])
    



print(minimum_number)

27
[{'start': 50, 'end': 98, 'increment': 2}, {'start': 98, 'end': 100, 'increment': -48}]


UnboundLocalError: local variable 'current_end' referenced before assignment

In [25]:
test_map = RangeMap()

test_map.add_mapping_rule(50,50 + 2, 98-50)
test_map.add_mapping_rule(52,52+48,50-52 )

values = np.array([50,52,1])

mapped_values = test_map.map_values(values)

mapped_values

[50. 52.  1.]
{'start': 50, 'end': 52, 'increment': 48}
[ True False False]
[98. 52.  1.]

[50. 52.  1.]
{'start': 52, 'end': 100, 'increment': -2}
[False  True False]
[98. 50.  1.]



array([98., 50.,  1.])

In [32]:
import numpy as np


seed_data = ['768975', '36881621', '56868281', '55386784', '1828225758', '1084205557']
seed_data_array = np.array(seed_data,dtype='int64')

values = np.concatenate([np.arange(start, start + end) for start, end in zip(seed_data_array[::2], seed_data_array[1::2])])

upper_limit = 388521182 + 141493697



# filtered_values_indices = np.where((values >= lower_limit) & (values <= upper_limit))

# values[filtered_values_indices] += 1


mask = (values >= lower_limit) & (values <= upper_limit)
values[mask] += 1


SyntaxError: invalid syntax (3921508153.py, line 9)